Send logs automatically after they have been captured
KanoComputing/kano-safe-mode pull request #4
Opened 2018-12-07 19:51 UTC by radujipa

Requires:
https://github.com/KanoComputing/kano-feedback/pull/93

2018-12-07 20:12 UTC, radujipa commented on src/kano_safe_mode_services/kano_safe_mode_send_logs.py
> +    if not os.path.exists(LOGS_PATH):
There is a catch here if a user:
 - had previously gone into safe mode and already have a `/boot/support_logs.tgz`
 - update to v4.2
this service will then send us the logs as if they've just gone into Safe Mode.

Changing the filename will likely create a second `.tgz` in `/boot/` and free space is precious there. We could add a post-update scenario to remove any existing logs if we don't want them.

2018-12-08 15:29 UTC, tombettany requested changes
Just a small problem with the service install configuration.

2018-12-08 15:29 UTC, tombettany commented on src/kano_safe_mode_services/kano_safe_mode_capture_logs.py
> +        return 10
Should add an RC module at some point.

2018-12-08 15:29 UTC, tombettany commented on conf/services/systemd/user/kano-safe-mode-send-logs.service
> +WantedBy=default.target
Shouldn't this be `WantedBy=kano-safe-mode-user.target`?

2018-12-08 16:25 UTC, radujipa commented on conf/services/systemd/user/kano-safe-mode-send-logs.service
> +WantedBy=default.target
I've hooked it up to `default.target` instead because if the service fails to send the logs on the Safe Mode boot, it might succeed sending them later on a normal boot.

2018-12-08 16:27 UTC, radujipa commented on src/kano_safe_mode_services/kano_safe_mode_capture_logs.py
> +        return 10
Should also put those checks in all services that need them.

2018-12-08 17:52 UTC, tombettany commented on conf/services/systemd/user/kano-safe-mode-send-logs.service
> +WantedBy=default.target
Fair enough, I'll merge in as is then :)

2018-12-08 17:52 UTC, tombettany approved these changes

2018-12-08 17:52 UTC, merged